### ISSUE TITLE
If Jean-Baptiste Glaire was a Hebraist, why is this translation called a Vulgate?

### ISSUE THREAD

**Issue by DavidHaslam** [MarjorieBurghart/VulgateGlaire#14]
Surely this notable French translation of the Bible was not _simply_ a translation from the Latin Vulgate,
even though it matches the _canon_ and _versification_ of the Vulgate!

Jean-Baptiste Glaire was a **Hebraist** and professor of Oriental Languages at the Sorbonne.

He would certainly have used his knowledge of the **Hebrew Bible** in his work of translating the Old Testament.

Isn't it therefore somewhat _misleading_ to call it **VulgateGlaire** ?

Better, rather, to call it **La Bible Glaire**, IMHO.

**Comment by DavidHaslam** [comment]
**Aside**: I've sometime heard it expressed the sentiment that "la Bible" is a Protestant word, and that Catholics often prefer the term "les Écritures".  Be that as it may, it shouldn't be used as a putative reason for French speaking Catholics not using the word "Bible", n'est-ce pas?

**Comment by MarjorieBurghart** [comment]
Hi David! 

No, this translation definitely *is* a translation of the Vulgate. It is a rather literal translation of the Latin Vulgate into French, and that is the main reason why I got interested into it in the first place (since I work on texts using the Latin Vulgate). Even if Glaire was a Hebraist, it stands to reason that a learned 19th cleric was also fluent in Latin. 

As for "Bible" vs. "les Écritures" in French, I have never heard of such a difference between Catholics and Protestants, to me the former is the mist common name, and the latter a more literary phrase.

**Comment by DavidHaslam** [comment]
Thanks for the explanation. @MarjorieBurghart 

Best wishes,

David
